apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-workload-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: dev-ops-0-dev-app-workload-sa@dev-ops-0.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-workload-sa-dummy
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: dev-ops-0-dev-dummy-sa@dev-ops-0.iam.gserviceaccount.com