---
- name: Orchestrate Full Stack Deployment
  hosts: localhost
  gather_facts: false
  vars:
    ray_tag: "latest"

  tasks:
    - name: Debug Deployment versions
      debug:
        msg: "Deploying: Ray:{{ ray_tag }}"

    - name: Deploy Ray Cluster + Ray Serve
      include_role:
        name: k8s_apply
      vars:
        ansible_search_path:
          - "{{ playbook_dir }}/../roles"
        templates:
          - "../roles/k8s_apply/templates/ray-service.yaml.j2"