---
- name: Orchestrate Full Stack Deployment
  hosts: localhost
  gather_facts: false
  vars_files:
    - "../inventory/dev/group_vars/all.yaml"
  vars:
    ray_tag: "latest"

  tasks:
    - name: Debug Deployment versions
      debug:
        msg: "Deploying: Ray:{{ ray_tag }}"

    - name: Deploy Ray Cluster + Ray Serve
      include_role:
        name: "{{ playbook_dir }}/../roles/k8s_apply"
      vars:
        templates:
          - "../roles/k8s_apply/templates/ray-service.yaml.j2"